### PR TITLE
fix: body null

### LINKED ISSUE #120: [BUG] "Cannot read property 'toLowerCase' of null" - empty issue bodies cause error when using 'check-issue'
### 🐛 Bug 描述 Bug description

When using `check-issue` - `body-includes` on an issue that has an empty body, the workflow fails with error:
`Error: [🚨 AC] Cannot read property 'toLowerCase' of null`

### 🏞 期望结果 Desired result

Desired result is that issues with empty body content can be reported as boolean. 

### 🚑 其他信息 Other information
Github "Convert to Issue" for task list items yields empty issues, which will break the above functionality.

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [x] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue
fix https://github.com/actions-cool/issues-helper/issues/120

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix body null case       |
| 🇨🇳 Chinese |           |

### CODE REVIEW

File: src/util/index.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ export const dealRandomAssignees = (assignees: string, randomTo: string | void):
   return arr;
 };
 
-export const matchKeyword = (content: string, keywords: string[]): boolean => {
+export const matchKeyword = (content: string = '', keywords: string[]): boolean => {
```
Comment (ajuner) [inline src/util/index.ts:12]: 👀

Comment (xrkffgg) [reply src/util/index.ts:12]: ？？？

Comment (madmansn0w) [reply src/util/index.ts:12]: This actually didn't resolve anything. The issue still exists. 
`Error: [🚨 AC] Cannot read properties of null (reading 'toLowerCase')` on v3.3.2 for issue with empty body and 
```sh
...
        with:
          actions: 'check-issue'
          body-includes: '###,Overview'
```
